### ISSUE TITLE
qheat_55_us not selectable on analyze website

### ISSUE THREAD

**Issue by kroimon** [wmbusmeters/wmbusmeters#1158]
### Type of request

Bug

### OS version

N/A

### wmbusmeters version

1.14.0-78-g866df74

### Your message goes here

Because of the underscores, the `qheat_55_us` driver can not be selected on https://wmbusmeters.org/

The error returned is
```
Not a valid meter driver "qheat55us"

Using: wmbusmeters: 1.16.1-23-gefcc41d
efcc41d107eaea1f78388386d4004b25112b0c04
```

**Comment by kroimon** [comment]
Not stale, still not working.

**Comment by weetmuts** [comment]
Fixed! Try now!

**Comment by kroimon** [comment]
Still doesn't work for me... https://wmbusmeters.org/analyze/1234:qheat55us

**Comment by kroimon** [comment]
Oooh it works now. I had to clear my cache for the dropdown to work.
👍
