### ISSUE TITLE
Add support for Engelmann Waterstar M (EFE, Water meter, Version 0x70)

### ISSUE THREAD

**Issue by BrewGnu** [wmbusmeters/wmbusmeters#1608]
### Type of request

New device support

## Meter Information
**Manufacturer:** Engelmann Sensor (EFE, 0x14c5)  
**Model:** Waterstar M  
**Meter ID:** 50494871  
**Type:** Water meter (0x07)  
**Version:** 0x70  
**Encryption:** AES_CBC_IV synchronous, CI=0x7a  

## Current Behavior
When using wmbusmeters version 1.19.0-10-g1027363, the meter is detected but no driver is available:
```
(meter) meter detection could not find driver for id: 50494871 mfct: (EFE) Engelmann Sensor, Germany (0x14c5) type: Water meter (0x07) ver: 0x70
```

## Raw Telegram
```
A144C5147148495070078C20467A83009025B759E1B9DFD432CAB46812D3C0F1E2DC6CDCF44E4CCC676C97DB765CF87B51D6BF75245676BF5794ED46BF838B5DC83E62B3931827EE5A0C506E8305EB88003E876968BB8823B861ECFDE786A424DF3E1C50862649FC40D41D59E99C1F9418B36E1EB1CB2AF8F591542A7787457C90523D9EC3216E0023FE989965AFA31AB79F02BE61D35668CC012137273C4C8D9B30
```

## Encryption Key
I have the encryption key from the vendor: `4F3F66E7AB473A2C092CAF00A4F20BA5`

When using this key, decryption fails with:
```
(wmbus) WARNING!! decrypted content failed check, did you use the correct decryption key?
```

The vendor has confirmed this is the correct key for this meter.

## Debug Information
```
(telegram) DLL L=a1 C=44 (from meter SND_NR) M=14c5 (EFE) A=50494871 VER=70 TYPE=07 (Water meter)
(telegram) ELL CI=8c CC=20 (slow_resp sync) ACC=46
(telegram) TPL CI=7a ACC=83 STS=00 CFG=2590 (synchronous AES_CBC_IV nb=9 cntn=0 ra=0 hc=0)
```

## Request
Could you please add support for this Engelmann Waterstar M meter variant? I'm happy to provide additional telegrams or test development versions.

## System Information
- **wmbusmeters version:** 1.19.0-10-g1027363
- **Device:** rtl_sdr with rtl_wmbus
- **Mode:** C1/T1

https://wmbusmeters.org/analyze/a144c5147148495070078c20467a83009025B759e1B9dfd432caB46812d3c0f1e2dc6cdcf44e4ccc676c97dB765cf87B51d6Bf75245676Bf5794ed46Bf838B5dc83e62B3931827ee5a0c506e8305eB88003e876968BB8823B861ecfde786a424df3e1c50862649fc40d41d59e99c1f9418B36e1eB1cB2af8f591542a7787457c90523d9ec3216e0023fe989965afa31aB79f02Be61d35668cc012137273c4c8d9B30:auto:4F3F66E7AB473A2C092CAF00A4F20BA5

### Logged telegrams from meter in decrypted format

```shell
-
```

**Comment by franzfranschitz-hash** [comment]
Hi,
I've the same problem. But how did you get the debug-data?
(telegram) DLL L=a1 C=44 (from meter SND_NR) M=14c5 (EFE) A=50494871 VER=70 TYPE=07 (Water meter)
BR

**Comment by prjh** [comment]
Hi,
this improvement is already merged to the master, [see](https://github.com/wmbusmeters/wmbusmeters/blob/71dde46c521fcc5b5004bba1cb42ea32fb9fde9e/src/driver_waterstarm.cc#L38C1-L38C51) - but not yet released :-)
Kind regards

**Comment by BrewGnu** [comment]
I installed this release (71dde46), and could read my telegram, because now the driver engelmann-faw exists. But it seems like I realy have a wrong key.
 
@franzfranschitz-hash I just ran 
wmbusmeters --analyze=terminal:engelmann-faw:MYKEY rtlwmbus
and waited for my meter-id.

**Comment by BrewGnu** [comment]
In addition to my post above: I have a new meter of the same type, and again the key seems to be wrong, I don't think this can appear twice. I tried drivers waterstarm an engelmann-faw.

Received telegram from: 50494869
          manufacturer: (EFE) Engelmann Sensor, Germany (0x14c5)
                  type: Water meter (0x07) encrypted
                   ver: 0x70
                device: rtlwmbus[72121394]
                  rssi: 128 dBm
                driver: waterstarm
telegram=|_A144C5146948495070078C202F7A6C0090254F7FAC2D0C9D1DFF35EE27CEE0DEEDA254437B4F9C61B95A89BBCBFAE90B3E31740D1CD16D6D8A1869F1064E03CDAD84E7E9B0922D842F32CF8E0894591E9AA8E8CA02DD3E6673EEB1B7D604D821A2E6855091DF05D23FFDED5B0132620947D191BCA38D4D87A971266C301CD7A25FE964113263A6C6EAF5F72EE91978B5AC72EDE8864C2290DBC3DCAD47FE035A485D|+184

The key is: DE8FC837909656ECB3C4D6AA343126F8

Here is the wmbusmeters-analysis: 

https://wmbusmeters.org/analyze/a144c5146948495070078c202f7a6c0090254f7fac2d0c9d1dff35ee27cee0deeda254437B4f9c61B95a89BBcBfae90B3e31740d1cd16d6d8a1869f1064e03cdad84e7e9B0922d842f32cf8e0894591e9aa8e8ca02dd3e6673eeB1B7d604d821a2e6855091df05d23ffded5B0132620947d191Bca38d4d87a971266c301cd7a25fe964113263a6c6eaf5f72ee91978B5ac72ede8864c2290dBc3dcad47fe035a485d:auto:DE8FC837909656ECB3C4D6AA343126F8

**Comment by prjh** [comment]
The right driver for this meter is **waterstarm**

**Comment by BrewGnu** [comment]
> The right driver for this meter is **sensostar**

But wmbusmeters-analysis (see link above) is not able to decode the telegram, even not with driver sensostar. What am I doing wrong?

**Comment by BrewGnu** [comment]
Is this issue solved? I still can't decrypt the telegrams of my engelmann waterstar M meters, no matter which meter type I use.

**Comment by prjh** [comment]
If you can clone the current master branch, I expect the problem is solved already. The question is why the repo maintainer does not decide to create a new release for all. I do not know the reasons about that.

**Comment by BrewGnu** [comment]
Hmmm... I compiled the master branch and started my metering script. wmbusmeters version is now 1.19.0-168-g6c25fed.
But it still can't decrypt the telegrams. I you click the links from my posts above (to the wmbusmeters-analysis), they also can't be decrypted. The version used there is 1.20.0...

@franzfranschitz-hash Did you solve you problems?

**Comment by Uzlopak** [comment]
There seems to be an issue with engelmann aes keys. It seems that the key has to be in the case of the original post `4F3F66E7AB473A2C092FAF00A4F20BA5`.

**Comment by BrewGnu** [comment]
Hi, thank you @Uzlopak! You're right. I've contacted engelmann an they recognized "a jumping bit" and corrected the key. Now everything works with this meter in mey wmbusmeters-system. 
Regarding the second meter, they told me, that the key is wrong, too, but they couldn't help me here, and told me to contact the distributor. Now I'm waiting for a set of an optical device and software to reprogram the key. I hope, I will get this done...

**Comment by Uzlopak** [comment]
NIce. I also contacted engelmann on [linkedin](https://www.linkedin.com/feed/update/urn:li:activity:7460969731357839360/?dashCommentUrn=urn%3Ali%3Afsd_comment%3A%287461954206954909696%2Curn%3Ali%3Aactivity%3A7460969731357839360%29).

> Vielen Dank für den Hinweis. Es war tatsächlich so, dass eine Version des Device Monitors an der 20ten Stelle des Hexadezimalen AES Schlüssels bzw. das 9 Byte fehlerhaft angezeigt wurde. Das betraff nur den WaterStar M und wurde längst behoben. Mit der Version 2.3.2 wird der AES Key korrekt dargestellt.

Which Optocoppler did you order?

**Comment by BrewGnu** [comment]
I didn't order it, my distributer suggested to send one to me for free for a week. I'm going to share this here, when it's done.

**Comment by BrewGnu** [comment]
It's so funny (or depressing in some way regarding all the time it needed to solve the problem)...
With your information, that it is the 20th part of the hex key, I just opened the wmbusmeters-analysis-link (see above) and tried to change this single position, starting with 1..2..3...4 and so on. It took exactly 9 tries :) So I don't need the optocoppler anymore...

**Comment by Uzlopak** [comment]
It's nice to hear that. I actually thought first, that you maybe made a typo. So I wrote a small script which tested for every combination when changing one hexadeximal position. I was quite happy when i found your key.

Then i tested the other telegram in the other issue, and was surprised that it was the same position. The confirmation from your supplier made me also very suspicious. 

I thought it is maybe a bit glitching. But in one case not only one bit glitched but two.

I also tried it also with your other telegram from your other meter, but did not get it cracked. Probably my script sucked. 

Anyhow: I can imagine how frustrating it can be, especially if they confirm that this is supposedly the right key. Anyhow: I am happy for you.
