### ISSUE TITLE
Nanocul stops responding after 12-16hours

### ISSUE THREAD

**Issue by hemandk** [wmbusmeters/wmbusmeters#567]
I have a Nanocul and it seems to work fine for 12-16hours and then I loose contact to it and I start to see the following error message

(wmbusmeters) logging started 2022-06-29 00:05:32 using 1.7.0-106-ge9d2846
[2022-06-29_00:05:34] Expected cul on /dev/ttyUSB0 but found unknown instead, ignoring it!
No wmbus device detected, waiting for a device to be plugged in.
(wmbusmeters) waiting for telegrams

I tried to make a script that runs every 12 hours, that does the following, but that also seems to have limited success. IE sometimes it manages to get going again and other times nothing happens.

sudo systemctl stop wmbusmeters
sleep 10
killall -9 wmbusmetersd
sleep 10
uhubctl -l 1-1 -p 2 -a off
sleep 300
uhubctl -l 1-1 -p 2 -a on
sleep 10
systemctl start wmbusmeters
sleep 120
killall -9 wmbusmetersd

**Comment by weetmuts** [comment]
I am not quite sure what this is. I have just pushed a fix where there was a problem when the wmbus dongle was reset (the default time between reset is 23 hours) and a telegram arrived exactly when wmbusmeters tried to set the link mode again.

Can you try the latest master and also try to provoke the problem with --resetafter=60s
which will reset the dongle every minute.

**Comment by weetmuts** [comment]
The nanocul takes a bit of time booting after it has been plugged in. Is this a restart after a power loss?

**Comment by hemandk** [comment]
I have tried setting the resetafter= 168h and it still happens after 12-16 hours.

There is no power loss or anything else, the nanocul just stops working after 12-16 hours and then I need to cut the power to the nanocul to get it going again.

I will try and update to latest version and set reset to 60s and see if the error occurs.

**Comment by hemandk** [comment]
How do I update, I tried to do sudo make install, but it just wants to install the 1.7 version?

**Comment by hemandk** [comment]
So I got it to update to 1.8.

I have made it reset every 24h and set logging to debug.

I will let it run and see what happens.

**Comment by hemandk** [comment]
So restarted the Nanucol and WMBusmeter the 2. of july at 09:21 and I can see and the log that is a restart at 3rd of july at 09:21 and everything contuines as it should.

Then the last message sent is at 3rd of july at 14:48 and last date written in the file is at 14:49:36 and then no more messages.

Looking at the log nothing, seems to go wrong but the Nanocul is not receiving anything telegrams anymore and it is flashing rapidly on the stick.

I think this might be an issue with the nanocul stick.

> (shell) arg "/usr/bin/mosquitto_pub -h 192.168.1.154 -u mqtt -P mqtt -t wmbusmeters/$METER_NAME -m "$METER_JSON" -r"
> (shell) env "METER_JSON={"media":"radio converter (meter side)","meter":"lse_07_17","name":"BryggersCold","id":"36724533","total_m3":3.119,"due_date_m3":0,"due_date":"2021-12-31","error_code":null,"error_date":"2127-15-31","device_date_time":"2022-07-03 14:48","timestamp":"2022-07-03T13:48:39Z","device":"cul","rssi_dbm":-21}"
> (shell) env "METER_ID=36724533"
> (shell) env "METER_NAME=BryggersCold"
> (shell) env "METER_MEDIA=radio converter (meter side)"
> (shell) env "METER_TYPE=lse_07_17"
> (shell) env "METER_TIMESTAMP=2022-07-03T13:48:39Z"
> (shell) env "METER_TIMESTAMP_UTC=2022-07-03T13:48:39Z"
> (shell) env "METER_TIMESTAMP_UT=1656856119"
> (shell) env "METER_TIMESTAMP_LT=2022-07-03 15:48.39"
> (shell) env "METER_DEVICE=cul"
> (shell) env "METER_RSSI_DBM=-21"
> (shell) env "METER_TOTAL_M3=3.119"
> (shell) env "METER_DUE_DATE_M3=0"
> (shell) env "METER_DUE_DATE=2021-12-31"
> (shell) env "METER_WHAT_DATE_M3=null"
> (shell) env "METER_WHAT_DATE=null"
> (shell) env "METER_ERROR_CODE=null"
> (shell) env "METER_ERROR_DATE=2127-15-31"
> (shell) env "METER_DEVICE_DATE_TIME=2022-07-03 14:48"
> (shell) env "METER_METER_VERSION=10"
> (shell) waiting for child 29451 to complete.
> (shell) /bin/sh: return code 0
> (wmbus) parseDLL @0 84
> (wmbus) parseELL @10 74
> (wmbus) parseNWL @10 74
> (wmbus) parseAFL @10 74
> (wmbus) parseTPL @10 74
> (meter) BryggersHot: for me? 36724533 in 36633633
> (meter) BryggersHot: not for me: not my id
> (wmbus) parseDLL @0 84
> (wmbus) parseELL @10 74
> (wmbus) parseNWL @10 74
> (wmbus) parseAFL @10 74
> (wmbus) parseTPL @10 74
> (meter) KitchenHot: for me? 36724533 in 36724180
> (meter) KitchenHot: not for me: not my id
> (wmbus) parseDLL @0 84
> (wmbus) parseELL @10 74
> (wmbus) parseNWL @10 74
> (wmbus) parseAFL @10 74
> (wmbus) parseTPL @10 74
> (meter) KitchenCold: for me? 36724533 in 36724629
> (meter) KitchenCold: not for me: not my id
> (serial) received binary "623145343432343233384230363135323732303633343934423741453130303130313730303844"
> (cul) checkCULFrame "b1E4424238B0615272063494B7AE1001017008D"
> (cul) no eol found yet, partial frame
> (serial) received binary "344546373944434444353432343445383239423236323336353533464542413632344130383731420D0A"
> (cul) checkCULFrame "b1E4424238B0615272063494B7AE1001017008D4EF79DCDD54244E829B26236553FEBA624A0871B<0D><0A>"
> (cul) checkCULFrame RSSI_RAW=27
> (cul) checkCULFrame LQI=67
> (wmbus) trimming frame A "1E4424238B0615272063494B7AE1001017008D4EF79DCDD54244E829B26236553FEBA624A0"
> (wmbus) ff a dll crc 0-9 494b ok
> (wmbus) ff a dll crc mid 12-27 b262 ok
> (wmbus) ff a dll crc final 30-34 24a0 ok
> (wmbus) trimming frame A "1E4424238B0615272063494B7AE1001017008D4EF79DCDD54244E829B26236553FEBA624A0"
> (wmbus) trimmed 6 dll crc bytes from frame a and ignored 0 suffix bytes.
> (wmbus) trimmed frame A "1E4424238B06152720637AE1001017008D4EF79DCDD54244E82936553FEBA6"
> (cul) received full T1 frame
> (diehl) preprocess necessary SWAPPING
> (diehl) Pre-processing: swapping address field
> (wmbus) parseDLL @0 31
> (wmbus) parseELL @10 21
> (wmbus) parseNWL @10 21
> (wmbus) parseAFL @10 21
> (wmbus) parseTPL @10 21
> (wmbus) non-standard security mode 16_31
> (diehl) frame REAL_DATA
> (diehl) must decode frame
> (meter) BryggersCold: for me? 63202715 in 36724533
> (meter) BryggersCold: not for me: not my id
> (diehl) preprocess necessary SWAPPING
> (diehl) Pre-processing: swapping address field
> (wmbus) parseDLL @0 31
> (wmbus) parseELL @10 21
> (wmbus) parseNWL @10 21
> (wmbus) parseAFL @10 21
> (wmbus) parseTPL @10 21
> (wmbus) non-standard security mode 16_31
> (diehl) frame REAL_DATA
> (diehl) must decode frame
> (meter) BryggersHot: for me? 63202715 in 36633633
> (meter) BryggersHot: not for me: not my id
> (diehl) preprocess necessary SWAPPING
> (diehl) Pre-processing: swapping address field
> (wmbus) parseDLL @0 31
> (wmbus) parseELL @10 21
> (wmbus) parseNWL @10 21
> (wmbus) parseAFL @10 21
> (wmbus) parseTPL @10 21
> (wmbus) non-standard security mode 16_31
> (diehl) frame REAL_DATA
> (diehl) must decode frame
> (meter) KitchenHot: for me? 63202715 in 36724180
> (meter) KitchenHot: not for me: not my id
> (diehl) preprocess necessary SWAPPING
> (diehl) Pre-processing: swapping address field
> (wmbus) parseDLL @0 31
> (wmbus) parseELL @10 21
> (wmbus) parseNWL @10 21
> (wmbus) parseAFL @10 21
> (wmbus) parseTPL @10 21
> (wmbus) non-standard security mode 16_31
> (diehl) frame REAL_DATA
> (diehl) must decode frame
> (meter) KitchenCold: for me? 63202715 in 36724629
> (meter) KitchenCold: not for me: not my id
> (meter) no meter handled 63202715 checking 4 templates.
> (diehl) preprocess necessary SWAPPING
> (diehl) Pre-processing: swapping address field
> (wmbus) parseDLL @0 31
> (wmbus) parseELL @10 21
> (wmbus) parseNWL @10 21
> (wmbus) parseAFL @10 21
> (wmbus) parseTPL @10 21
> (wmbus) non-standard security mode 16_31
> (diehl) frame REAL_DATA
> (diehl) must decode frame
> (meter) BryggersCold: for me? 63202715 in 36724533
> (meter) BryggersCold: not for me: not my id
> (meter) KitchenCold: for me? 63202715 in 36724629
> (meter) KitchenCold: not for me: not my id
> (meter) KitchenHot: for me? 63202715 in 36724180
> (meter) KitchenHot: not for me: not my id
> (meter) BryggersHot: for me? 63202715 in 36633633
> (meter) BryggersHot: not for me: not my id
> (wmbus) telegram from 63202715 ignored by all configured meters!
> (serial) received binary "62334334343933"
> (cul) checkCULFrame "b3C4493"
> (cul) no eol found yet, partial frame
> (serial) received binary "34343335343637323336333533374233463137323335343637323336393334343335303731343030303032303043313339313942414633313030303034433133303030303030303034323643424632434343303831333346304439353237303030304332303836434445323633323643464646463034364433"
> (cul) checkCULFrame "b3C449344354672363537B3F1723546723693443507140000200C13919BAF3100004C1300000000426CBF2CCC08133F0D95270000C2086CDE26326CFFFF046D3"
> (cul) no eol found yet, partial frame
> (serial) received binary "313245423630454333323731453032383634460D0A"
> (cul) checkCULFrame "b3C449344354672363537B3F1723546723693443507140000200C13919BAF3100004C1300000000426CBF2CCC08133F0D95270000C2086CDE26326CFFFF046D312EB60EC3271E02864F<0D><0A>"
> (cul) checkCULFrame RSSI_RAW=79
> (cul) checkCULFrame LQI=67
> (wmbus) trimming frame A "3C449344354672363537B3F1723546723693443507140000200C13919BAF3100004C1300000000426CBF2CCC08133F0D95270000C2086CDE26326CFFFF046D312EB60EC3271E02"
> (wmbus) ff a dll crc 0-9 b3f1 ok
> (wmbus) ff a dll crc mid 12-27 9baf ok
> (wmbus) ff a dll crc mid 30-45 3f0d ok
> (wmbus) ff a dll crc mid 48-63 2eb6 ok
> (wmbus) ff a dll crc final 66-68 1e02 ok
> (wmbus) trimming frame A "3C449344354672363537B3F1723546723693443507140000200C13919BAF3100004C1300000000426CBF2CCC08133F0D95270000C2086CDE26326CFFFF046D312EB60EC3271E02"
> (wmbus) trimmed 10 dll crc bytes from frame a and ignored 0 suffix bytes.
> (wmbus) trimmed frame A "3C449344354672363537723546723693443507140000200C13913100004C1300000000426CBF2CCC081395270000C2086CDE26326CFFFF046D310EC327"
> (cul) received full T1 frame
> (wmbus) parseDLL @0 61
> (wmbus) parseELL @10 51
> (wmbus) parseNWL @10 51
> (wmbus) parseAFL @10 51
> (wmbus) parseTPL @10 51
> (meter) BryggersCold: for me? 36724635,36724635 in 36724533
> (meter) BryggersCold: not for me: not my id
> (wmbus) parseDLL @0 61
> (wmbus) parseELL @10 51
> (wmbus) parseNWL @10 51
> (wmbus) parseAFL @10 51
> (wmbus) parseTPL @10 51
> (meter) BryggersHot: for me? 36724635,36724635 in 36633633
> (meter) BryggersHot: not for me: not my id
> (wmbus) parseDLL @0 61
> (wmbus) parseELL @10 51
> (wmbus) parseNWL @10 51
> (wmbus) parseAFL @10 51
> (wmbus) parseTPL @10 51
> (meter) KitchenHot: for me? 36724635,36724635 in 36724180
> (meter) KitchenHot: not for me: not my id
> (wmbus) parseDLL @0 61
> (wmbus) parseELL @10 51
> (wmbus) parseNWL @10 51
> (wmbus) parseAFL @10 51
> (wmbus) parseTPL @10 51
> (meter) KitchenCold: for me? 36724635,36724635 in 36724629
> (meter) KitchenCold: not for me: not my id
> (meter) no meter handled 36724635,36724635 checking 4 templates.
> (wmbus) parseDLL @0 61
> (wmbus) parseELL @10 51
> (wmbus) parseNWL @10 51
> (wmbus) parseAFL @10 51
> (wmbus) parseTPL @10 51
> (meter) BryggersCold: for me? 36724635,36724635 in 36724533
> (meter) BryggersCold: not for me: not my id
> (meter) KitchenCold: for me? 36724635,36724635 in 36724629
> (meter) KitchenCold: not for me: not my id
> (meter) KitchenHot: for me? 36724635,36724635 in 36724180
> (meter) KitchenHot: not for me: not my id
> (meter) BryggersHot: for me? 36724635,36724635 in 36633633
> (meter) BryggersHot: not for me: not my id
> (wmbus) telegram from 36724635,36724635 ignored by all configured meters!
> (serial) received binary "623533343439333434333834353732333633353337464445453738303737393338343537323336"
> (cul) checkCULFrame "b53449344384572363537FDEE78077938457236"
> (cul) no eol found yet, partial frame
> (serial) received binary "39333434333530373044464635463335303044344633383236423030303038303030303743313133464646463435313430303030424633394344324330303030303030304445323630353133303030303030383030303830303039374633383030303030303030303030303030303030303030303030303030"
> (cul) checkCULFrame "b53449344384572363537FDEE78077938457236934435070DFF5F3500D4F3826B0000800007C113FFFF45140000BF39CD2C00000000DE2605130000008000800097F3800000000000000000000000000"
> (cul) no eol found yet, partial frame
> (serial) received binary "303030303043453444303038323030324630343644333130454333323732364237383732390D0A"
> (cul) checkCULFrame "b53449344384572363537FDEE78077938457236934435070DFF5F3500D4F3826B0000800007C113FFFF45140000BF39CD2C00000000DE2605130000008000800097F380000000000000000000000000000000CE4D0082002F046D310EC32726B78729<0D><0A>"
> (cul) checkCULFrame RSSI_RAW=41
> (cul) checkCULFrame LQI=67
> (wmbus) trimming frame A "53449344384572363537FDEE78077938457236934435070DFF5F3500D4F3826B0000800007C113FFFF45140000BF39CD2C00000000DE2605130000008000800097F380000000000000000000000000000000CE4D0082002F046D310EC32726B7"
> (wmbus) ff a dll crc 0-9 fdee ok
> (wmbus) ff a dll crc mid 12-27 d4f3 ok
> (wmbus) ff a dll crc mid 30-45 39cd ok
> (wmbus) ff a dll crc mid 48-63 97f3 ok
> (wmbus) ff a dll crc mid 66-81 ce4d ok
> (wmbus) ff a dll crc final 84-93 26b7 ok
> (wmbus) trimming frame A "53449344384572363537FDEE78077938457236934435070DFF5F3500D4F3826B0000800007C113FFFF45140000BF39CD2C00000000DE2605130000008000800097F380000000000000000000000000000000CE4D0082002F046D310EC32726B7"
> (wmbus) trimmed 12 dll crc bytes from frame a and ignored 0 suffix bytes.
> (wmbus) trimmed frame A "5344934438457236353778077938457236934435070DFF5F3500826B0000800007C113FFFF45140000BF2C00000000DE26051300000080008000800000000000000000000000000000000082002F046D310EC327"
> (cul) received full T1 frame
> (wmbus) parseDLL @0 84
> (wmbus) parseELL @10 74
> (wmbus) parseNWL @10 74
> (wmbus) parseAFL @10 74
> (wmbus) parseTPL @10 74
> (meter) BryggersCold: for me? 36724538 in 36724533
> (meter) BryggersCold: not for me: not my id
> (wmbus) parseDLL @0 84
> (wmbus) parseELL @10 74
> (wmbus) parseNWL @10 74
> (wmbus) parseAFL @10 74
> (wmbus) parseTPL @10 74
> (meter) BryggersHot: for me? 36724538 in 36633633
> (meter) BryggersHot: not for me: not my id
> (wmbus) parseDLL @0 84
> (wmbus) parseELL @10 74
> (wmbus) parseNWL @10 74
> (wmbus) parseAFL @10 74
> (wmbus) parseTPL @10 74
> (meter) KitchenHot: for me? 36724538 in 36724180
> (meter) KitchenHot: not for me: not my id
> (wmbus) parseDLL @0 84
> (wmbus) parseELL @10 74
> (wmbus) parseNWL @10 74
> (wmbus) parseAFL @10 74
> (wmbus) parseTPL @10 74
> (meter) KitchenCold: for me? 36724538 in 36724629
> (meter) KitchenCold: not for me: not my id
> (meter) no meter handled 36724538 checking 4 templates.
> (wmbus) parseDLL @0 84
> (wmbus) parseELL @10 74
> (wmbus) parseNWL @10 74
> (wmbus) parseAFL @10 74
> (wmbus) parseTPL @10 74
> (meter) BryggersCold: for me? 36724538 in 36724533
> (meter) BryggersCold: not for me: not my id
> (meter) KitchenCold: for me? 36724538 in 36724629
> (meter) KitchenCold: not for me: not my id
> (meter) KitchenHot: for me? 36724538 in 36724180
> (meter) KitchenHot: not for me: not my id
> (meter) BryggersHot: for me? 36724538 in 36633633
> (meter) BryggersHot: not for me: not my id
> (wmbus) telegram from 36724538 ignored by all configured meters!
>

**Comment by weetmuts** [comment]
Yes, flashing rapidly does not sound that good. 

However the problem of wmbus dongles suddenly stopping relaying telegrams is the
reason why I added --resetafter=23h as the default setting.

The im871a did after a week or so of running suddenly turn silent, and since
wmbusmeters at that time never sent any more instructions to it, after the initial setup.
It could not have been wmbusmeters fault. 

So if your nano-cul misbehaves after 16 hours, can you test --resetafter=10h to see if
preemptively closing/opening the serial port and resending the link mode command is enough to keep it going. Probably not, if it is flashing, but can you test anyway?

**Comment by hemandk** [comment]
Yes I will do that and report back.

**Comment by AndrewSpec** [comment]
I have the same problem. I've made a usbreset app to resolve my issue but now even unpluging my nanocul don't work.

`(wmbusmeters) logging started 2022-07-07 02:42:35 using 1.6.0
(wmbusmeters) version: 1.6.0
(config) store meter files in: "/var/log/wmbusmeters/meter_readings"
(config) using device: /dev/ttyUSB0:cul:t1
(config) number of meters: 2
(lookup) with file/hex "/dev/ttyUSB0"
(serial) check if /dev/ttyUSB0 can be accessed
(serial) tty /dev/ttyUSB0 can be accessed
(serial) before config: /dev/ttyUSB0 speed(B9600) input(ICRNL|IXON) output(ONLCR|OPOST) control(CLOCAL|CREAD|CSIZE|HUPCL) local(ECHO|ECHOCTL|ECHOE|ECHOK|ECHOKE|ICANON|IEXTEN|ISIG) special_chars(3,28,127,21,4,1,17,19,26,18,15,23,22) modem(DTR|RTS)
(serial) after config:  /dev/ttyUSB0 speed(B9600) input() output() control(CLOCAL|CREAD|CSIZE) local() special_chars() modem(DTR|RTS)
(serialtty) opened /dev/ttyUSB0 fd 4 (detect amb8465)
(serial) received binary ""
(amb8465) sending 6 bytes attempt 0
(serial /dev/ttyUSB0) sent "FF0A02008077"
(amb8465) sent 6 bytes OK
(serial) EVENT thread interrupted
(amb8465) reading response... 1
(serial) received binary ""
(amb8465) reading response... 2
(serial) received binary ""
(amb8465) reading response... 3
(serial) received binary ""
(amb8465) are you there? no.
(serialtty) closed /dev/ttyUSB0 (detect amb8465)
(serial) EVENT thread interrupted
(serial) before config: /dev/ttyUSB0 speed(B9600) input() output() control(CLOCAL|CREAD|CSIZE) local() special_chars() modem(DTR|RTS)
(serial) after config:  /dev/ttyUSB0 speed(B57600) input() output() control(CLOCAL|CREAD|CSIZE) local() special_chars() modem(DTR|RTS)
(serialtty) opened /dev/ttyUSB0 fd 5 (detect im871a)
(serial) received binary ""
(serial /dev/ttyUSB0) sent "A5010F00"
(serial) EVENT thread interrupted
(serial) received binary ""
(im871a/im170a) are you there? no.
(serialtty) closed /dev/ttyUSB0 (detect im871a)
(serial) EVENT thread interrupted
(serial) before config: /dev/ttyUSB0 speed(B57600) input() output() control(CLOCAL|CREAD|CSIZE) local() special_chars() modem(DTR|RTS)
(serial) after config:  /dev/ttyUSB0 speed(B19200) input() output() control(CLOCAL|CREAD|CSIZE) local() special_chars() modem(DTR|RTS)
(serialtty) opened /dev/ttyUSB0 fd 4 (detect rc1180)
(serial /dev/ttyUSB0) sent "00"
(serial) EVENT thread interrupted
(serial) received binary ""
(serial /dev/ttyUSB0) sent "30"
(serial) EVENT thread interrupted
(serial) received binary ""
(serialtty) closed /dev/ttyUSB0 (detect rc1180)
(rc1180) are you there? no.
(serial) EVENT thread interrupted
(serial) before config: /dev/ttyUSB0 speed(B19200) input() output() control(CLOCAL|CREAD|CSIZE) local() special_chars() modem(DTR|RTS)
(serial) after config:  /dev/ttyUSB0 speed(B38400) input() output() control(CLOCAL|CREAD|CSIZE) local() special_chars() modem(DTR|RTS)
(serialtty) opened /dev/ttyUSB0 fd 4 (detect cul)
(serial /dev/ttyUSB0) sent "560A0D"
(serial) EVENT thread interrupted
(serial) received binary "5620"
(cul) probe response "V "
(serial /dev/ttyUSB0) sent "560A0D"
(serial) EVENT thread interrupted
(serial) received binary "5620"
(cul) probe response "V "
(serial /dev/ttyUSB0) sent "560A0D"
(serial) EVENT thread interrupted
(serial) received binary ""
(cul) probe response ""
(serialtty) closed /dev/ttyUSB0 (detect cul)
(cul) are you there? no
[2022-07-07_02:42:38] Expected cul on /dev/ttyUSB0 but found unknown instead, ignoring it!
(verbose) ignoring device t1
No wmbus device detected, waiting for a device to be plugged in.
(shell) exec (capture output) "/bin/pidof"
(shell) arg "wmbusmetersd"
(serial) EVENT thread interrupted
(shell) output: >>>4577
<<<`

I'm using that device https://www.ebay.com/itm/372221622516

**Comment by hemandk** [comment]
So setting reset to 10h does not help the issue

**Comment by AndrewSpec** [comment]
In my case I needed to reflash the arduino nano and then it started working...

**Comment by hemandk** [comment]
Started working without a reset every 10-12h or do you still need that?

**Comment by AndrewSpec** [comment]
> Started working without a reset every 10-12h or do you still need that?

I reset it every hour. Reflashing solved the issue that device was not recognized as a CUL.

**Comment by weetmuts** [comment]
Ok so it is a cul problem. There is an improved binary that can handle slightly longer telegrams here:
https://weetmuts.github.io/wmbusmeterswiki/nanoCUL.html

**Comment by hemandk** [comment]
I had smart-home-componenten.de flash it, as per the suggestion in the wiki. I assume that is the firmware you are linking to?

**Comment by weetmuts** [comment]
No, that firmware is specially built by a wmbusmeters user who discovered that the serial buffer was too small, so telegrams were truncated. wmbusmeters now detects this and warns that it could be a bad cul firmware.

https://github.com/weetmuts/wmbusmeters/issues/390

**Comment by weetmuts** [comment]
A sorry, you have flashed (asked the company) the specific firmware supplied on the wiki?

**Comment by hemandk** [comment]
Yes I asked them to flash the wmbusmeters firmware, they have flashed the following file:
nanoCUL_r568_mbus_c1t1_bufsize300.hex

**Comment by torliPL** [comment]
I've encounter the problem with the reset procedure. After commiting a reset the dongle won't present any more and need to replug the dongle and sometimes even reset HA addon.
The problem was with the clone version of Arduino Nano. I've change it to original one, and everything is working as expected. Reset occurs every 23h, everything is ok.
Somehow the clone Arduino Nano don't work correctly.

**Comment by torliPL** [comment]
> 
> I'm using that device https://www.ebay.com/itm/372221622516

This Arduino Nano is clone and it's not working correctly, especially with the reset procedure. After software reset You will need to replug the dongle. Use only original Arduino Nano board.

**Comment by oktett-8** [comment]
Fixed in #1437 .
